from gym_soccer.envs.soccer_env import SoccerEnv, SoccerEnvInit
from gym_soccer.envs.soccer_empty_goal import SoccerEmptyGoalEnv
from gym_soccer.envs.soccer_against_keeper import SoccerAgainstKeeperEnv
